name: my_note
description: "A simple app for secure notes"
publish_to: "none"

version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Encryption
  encrypt: ^5.0.3
  crypto: ^3.0.3
  # UI & Utility
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3

  # Data storage
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # File management
  file_picker: ^8.1.2
  open_filex: ^4.5.0

  # Preferences (optional untuk pengaturan warna tema, dsb)
  shared_preferences: ^2.2.3

  # Icon generator
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
flutter_icons:
  android: "launcher_icon" # Atau beri nama spesifik, misalnya "my_app_icon"
  ios: true # Set ke true untuk iOS
  image_path: "assets/logo.png" # Ganti dengan path icon Anda
  # Opsional: untuk Adaptive Icons di Android (hanya untuk Android)
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
